"""Service layer: the seam between the pure engine and the database.  # SPEC §7, §8

``engine/`` never touches I/O; ``api/`` never touches the engine directly. Everything that
loads a deal, assembles typed inputs, runs the math, and records the result lives here.

Every write here takes an ``actor`` and records an ``audit_log`` row beside what it changed
(SPEC §5, §11). Nothing here commits: the caller owns the transaction, so a change and its
audit row land together or not at all.
"""

from __future__ import annotations

from services.actions import (
    ADVANCE_TO_REVIEW_FROM,
    DECLINE_FROM,
    MARK_DEAD_FROM,
    PAUSE_FROM,
    PROGRESS_FROM,
    REOPEN_FROM,
    RESUME_FROM,
    add_note,
    advance_to_review,
    apply_overrides,
    decline,
    mark_dead,
    pause,
    paused_from,
    progress,
    reopen,
    reopen_status,
    resume,
    save_overrides,
)
from services.audit import DEALS, USERS, deal_trail, jsonable, last_action_at, record_audit
from services.autorun import NOTHING_RAN, SYSTEM_ACTOR, AutoRun, auto_run, run_analysis
from services.defaults import (
    DEFAULTABLE,
    apply_defaults,
    default_closing_date,
    default_loan_split,
    defaults_for,
    economics_defaults,
    is_defaulted,
    populate,
    submitted_on,
)
from services.enrichment import NO_ADAPTER_VALUES, AdapterValues, adapter_values
from services.errors import (
    ActionNotAllowed,
    DealNotFound,
    DealNotPriceable,
    DealNotReady,
    DealNotUnderwritable,
    ReasonRequired,
    ServiceError,
    UserExists,
    UserNotFound,
)
from services.history import HistoryEntry, HistoryKind, deal_history
from services.home import (
    SECTION_TITLES,
    HomeEntry,
    HomeSection,
    HomeView,
    Section,
    home_view,
    last_activity,
    section_of,
)
from services.intake import (
    EDIT_INTAKE_FROM,
    create_deal,
    latest_submission,
    record_from_submission,
    restore_intake,
    screen_is_stale,
    update_intake,
)
from services.lifecycle import (
    advance_after_screen,
    advance_for_underwrite,
    check_intake_complete,
    check_underwritable,
    status_after_screen,
    status_after_underwrite,
)
from services.passwords import WeakPassword, hash_password, verify_password
from services.persistence import (
    latest_screen,
    latest_underwrite,
    record_screen,
    record_underwrite,
    screen_result,
    underwrite_result,
)
from services.purge import purge_deals
from services.readiness import (
    InputRow,
    InputSource,
    UnderwriteReadiness,
    underwrite_readiness,
)
from services.requests import TeamOverrides, UnderwriteRequest
from services.runner import load_deal, run_screen, run_underwrite
from services.users import (
    authenticate,
    create_user,
    deactivate_user,
    get_user,
    list_users,
    normalize_email,
    user_by_email,
)

__all__ = [
    "ADVANCE_TO_REVIEW_FROM",
    "DEALS",
    "DECLINE_FROM",
    "DEFAULTABLE",
    "EDIT_INTAKE_FROM",
    "MARK_DEAD_FROM",
    "NOTHING_RAN",
    "NO_ADAPTER_VALUES",
    "PAUSE_FROM",
    "PROGRESS_FROM",
    "REOPEN_FROM",
    "RESUME_FROM",
    "SECTION_TITLES",
    "SYSTEM_ACTOR",
    "USERS",
    "ActionNotAllowed",
    "AdapterValues",
    "AutoRun",
    "DealNotFound",
    "DealNotPriceable",
    "DealNotReady",
    "DealNotUnderwritable",
    "HistoryEntry",
    "HistoryKind",
    "HomeEntry",
    "HomeSection",
    "HomeView",
    "InputRow",
    "InputSource",
    "ReasonRequired",
    "Section",
    "ServiceError",
    "TeamOverrides",
    "UnderwriteReadiness",
    "UnderwriteRequest",
    "UserExists",
    "UserNotFound",
    "WeakPassword",
    "adapter_values",
    "add_note",
    "advance_after_screen",
    "advance_for_underwrite",
    "advance_to_review",
    "apply_defaults",
    "apply_overrides",
    "auto_run",
    "authenticate",
    "check_intake_complete",
    "check_underwritable",
    "create_deal",
    "create_user",
    "deactivate_user",
    "deal_history",
    "deal_trail",
    "decline",
    "default_closing_date",
    "default_loan_split",
    "defaults_for",
    "economics_defaults",
    "get_user",
    "hash_password",
    "home_view",
    "is_defaulted",
    "jsonable",
    "last_action_at",
    "last_activity",
    "latest_screen",
    "latest_submission",
    "latest_underwrite",
    "list_users",
    "load_deal",
    "mark_dead",
    "normalize_email",
    "pause",
    "paused_from",
    "populate",
    "progress",
    "purge_deals",
    "record_audit",
    "record_screen",
    "record_from_submission",
    "record_underwrite",
    "reopen",
    "reopen_status",
    "restore_intake",
    "resume",
    "run_analysis",
    "run_screen",
    "run_underwrite",
    "save_overrides",
    "screen_is_stale",
    "screen_result",
    "section_of",
    "status_after_screen",
    "status_after_underwrite",
    "submitted_on",
    "underwrite_readiness",
    "underwrite_result",
    "update_intake",
    "user_by_email",
    "verify_password",
]
